import Head from 'next/head';
import axios from 'axios';
import buildClient from './api/build-client';

export default function Home({ currentUser }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{currentUser ? 'You are signed in' : 'You are NOT signed in'}</h1>
    </div>
  );
}

export async function getServerSideProps(context) {
  const client = buildClient(context);
  const { data } = await client.get('/api/users/currentuser');
  return {
    props: {
      currentUser: data.currentUser
    }
  };
}
