apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: ghislaingenay/ticket-orders
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'tickets'
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: dev-secret
                  key: MONGO_URI
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dev-secret
                  key: JWT_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec: # Didn't add the type of service => Default is ClusterIP
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
